Fix for flapping context tests
Some of the tests assumed that the cancellation was already
propagated so were failing occasionally:

```
--- FAIL: TestOldContextRequestWithTimeoutCanceled (0.03s)
	context_test.go:141: Expected request with timeout context to fail: %!s(<nil>)
```

In order to prevent this, added an extra wait to the context tests
and wait for context to be detected as cancelled.

Signed-off-by: Waldemar Quevedo <wally@synadia.com>